### ISSUE TITLE
Installing flake8-isort 5.0.2 breaks flake8 5.0.4

### ISSUE THREAD

**Issue by balgillo** [gforcada/flake8-isort#128]
Installing flake8-isort 5.0.2 breaks flake8 5.0.4.

```
flake8 --help
Traceback (most recent call last):
  File "/home/developer/.local/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/home/developer/.local/lib/python3.8/site-packages/flake8/main/cli.py", line 22, in main
    app.run(argv)
  File "/home/developer/.local/lib/python3.8/site-packages/flake8/main/application.py", line 336, in run
    self._run(argv)
  File "/home/developer/.local/lib/python3.8/site-packages/flake8/main/application.py", line 324, in _run
    self.initialize(argv)
  File "/home/developer/.local/lib/python3.8/site-packages/flake8/main/application.py", line 308, in initialize
    self.register_plugin_options()
  File "/home/developer/.local/lib/python3.8/site-packages/flake8/main/application.py", line 140, in register_plugin_options
    self.option_manager.register_plugins(self.plugins)
  File "/home/developer/.local/lib/python3.8/site-packages/flake8/options/manager.py", line 376, in register_plugins
    add_options(self)
TypeError: add_options() missing 1 required positional argument: 'option_manager'
```

This is fixed by downgrading `pip install flake8-isort==5.0.0`.  5.0.1 is OK for `flake8 --help` but fails with `TypeError: parse_options() missing 3 required positional arguments: 'option_manager', 'options', and 'args'` for `flake8 .`

**Comment by gforcada** [comment]
Thanks, there is a PR ready, this time, rather than merging and releasing, I will properly test it myself: 😅

**Comment by GideonBear** [comment]
@gforcada please yank `5.0.1` and `5.0.2`, as they're both completely broken. Keeping them will probably scare away a lot of users, if they are yanked pip will automatically install `5.0.0`.

**Comment by gforcada** [comment]
@GideonBear good idea 💯 I never actually looked what this yanking of releases was for, but indeed, that's a good idea 👍🏾

**Comment by gforcada** [comment]
Done! 🐢

**Comment by balgillo** [comment]
I can confirm that flake8-isort 5.0.3 doesn't have these issues.  Thanks for the prompt action!
