### ISSUE TITLE
does not work with newly released flake8 3.0.0

### ISSUE THREAD

**Issue by AnneGilles** [gforcada/flake8-isort#13]
```
Traceback (most recent call last):
  File "/home/christoph/Code/unimr.sitemapimport/bin/flake8", line 34, in <module>
    sys.exit(flake8.main.cli.main())
  File "/home/christoph/Code/unimr.sitemapimport/eggs/flake8-3.0.0-py2.7.egg/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/home/christoph/Code/unimr.sitemapimport/eggs/flake8-3.0.0-py2.7.egg/flake8/main/application.py", line 299, in run
    self._run(argv)
  File "/home/christoph/Code/unimr.sitemapimport/eggs/flake8-3.0.0-py2.7.egg/flake8/main/application.py", line 285, in _run
    self.initialize(argv)
  File "/home/christoph/Code/unimr.sitemapimport/eggs/flake8-3.0.0-py2.7.egg/flake8/main/application.py", line 276, in initialize
    self.register_plugin_options()
  File "/home/christoph/Code/unimr.sitemapimport/eggs/flake8-3.0.0-py2.7.egg/flake8/main/application.py", line 150, in register_plugin_options
    self.check_plugins.register_options(self.option_manager)
  File "/home/christoph/Code/unimr.sitemapimport/eggs/flake8-3.0.0-py2.7.egg/flake8/plugins/manager.py", line 451, in register_options
    list(self.manager.map(register_and_enable))
  File "/home/christoph/Code/unimr.sitemapimport/eggs/flake8-3.0.0-py2.7.egg/flake8/plugins/manager.py", line 261, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "/home/christoph/Code/unimr.sitemapimport/eggs/flake8-3.0.0-py2.7.egg/flake8/plugins/manager.py", line 447, in register_and_enable
    call_register_options(plugin)
  File "/home/christoph/Code/unimr.sitemapimport/eggs/flake8-3.0.0-py2.7.egg/flake8/plugins/manager.py", line 357, in generated_function
    return method(optmanager, *args, **kwargs)
  File "/home/christoph/Code/unimr.sitemapimport/eggs/flake8-3.0.0-py2.7.egg/flake8/plugins/manager.py", line 207, in register_options
    add_options(optmanager)
  File "/home/christoph/Code/unimr.sitemapimport/eggs/flake8_isort-1.3-py2.7.egg/flake8_isort.py", line 43, in add_options
    parser.config_options.append('no-isort-config')
AttributeError: 'OptionManager' object has no attribute 'config_options'
christoph@pcrz547:~/Code/unimr.sitemapimport$
```

**Comment by gforcada** [comment]
@AnneGilles thanks for reporting! I still haven't had the time to try (I didn't even know!) flake8 3.0.

If you have the skills, would you mind providing a pull request? If not it will take a while as I will on vacations for a few days

**Comment by gforcada** [comment]
@AnneGilles @danpalmer 2.0 release is out, please give it a try!

**Comment by AnneGilles** [comment]
@gforcada works for us (as in: gets selected by buildout and installed, seems to do its job: I have not introduced unordered imports to actually trigger it) with latest flake8 3.0.4. Thanks!
