### ISSUE TITLE
exception on empty __init__.py files

### ISSUE THREAD

**Issue by mnencia** [gforcada/flake8-isort#21]
On version 2.1.0 and 2.1.1, empty `__init__.py` files triggers an exception. 

```
$ > __init__.py
$ flake8 __init__.py
Process Process-1:
Traceback (most recent call last):
  File "/Users/mnencia/.pyenv/versions/2.7.12/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Users/mnencia/.pyenv/versions/2.7.12/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/mnencia/.pyenv/versions/2.7.12/envs/test/lib/python2.7/site-packages/flake8/checker.py", line 666, in _run_checks_from_queue
    checker.run_checks(results_queue, statistics_queue)
  File "/Users/mnencia/.pyenv/versions/2.7.12/envs/test/lib/python2.7/site-packages/flake8/checker.py", line 606, in run_checks
    self.run_ast_checks()
  File "/Users/mnencia/.pyenv/versions/2.7.12/envs/test/lib/python2.7/site-packages/flake8/checker.py", line 517, in run_ast_checks
    for (line_number, offset, text, check) in runner:
  File "/Users/mnencia/.pyenv/versions/2.7.12/envs/test/lib/python2.7/site-packages/flake8_isort.py", line 70, in run
    for line_num, message in self.sortimports_linenum_msg(sort_result):
  File "/Users/mnencia/.pyenv/versions/2.7.12/envs/test/lib/python2.7/site-packages/flake8_isort.py", line 116, in sortimports_linenum_msg
    self._fixup_sortimports_wrapped(sort_result)
  File "/Users/mnencia/.pyenv/versions/2.7.12/envs/test/lib/python2.7/site-packages/flake8_isort.py", line 172, in _fixup_sortimports_wrapped
    for idx, line in enumerate(sort_imports.out_lines):
AttributeError: 'SortImports' object has no attribute 'out_lines'
```

On 2.0.3 it works as expected.

Empty files with a different name don't trigger the error.

**Comment by cas--** [comment]
There is a fix in `2.1.1` for empty `__init__.py` files and I cannot replicate this, what version of flake8 and isort?

**Comment by mnencia** [comment]
The virtualenv was freshly created. However here the pip freeze output:

```
10:46 $ pip freeze
configparser==3.5.0
enum34==1.1.6
flake8==3.2.1
flake8-isort==2.1.1
flake8-polyfill==1.0.1
isort==4.2.5
mccabe==0.5.2
pycodestyle==2.2.0
pyflakes==1.3.0
testfixtures==4.13.1
```

Python version is 2.7.12

I also tried to replicate it outside my project home, to exclude it is dependent from the tox and isort configuration, so I tried it in my $HOME directory:

```
10:48 $ touch .isort.cfg
(test) ✔ ~
10:48 $ flake8 __init__.py
Traceback (most recent call last):
  File "/Users/mnencia/.pyenv/versions/test/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/Users/mnencia/.pyenv/versions/2.7.12/envs/test/lib/python2.7/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/Users/mnencia/.pyenv/versions/2.7.12/envs/test/lib/python2.7/site-packages/flake8/main/application.py", line 322, in run
    self._run(argv)
  File "/Users/mnencia/.pyenv/versions/2.7.12/envs/test/lib/python2.7/site-packages/flake8/main/application.py", line 306, in _run
    self.run_checks()
  File "/Users/mnencia/.pyenv/versions/2.7.12/envs/test/lib/python2.7/site-packages/flake8/main/application.py", line 243, in run_checks
    self.file_checker_manager.start(files)
  File "/Users/mnencia/.pyenv/versions/2.7.12/envs/test/lib/python2.7/site-packages/flake8/checker.py", line 371, in start
    self.make_checkers(paths)
  File "/Users/mnencia/.pyenv/versions/2.7.12/envs/test/lib/python2.7/site-packages/flake8/checker.py", line 285, in make_checkers
    if argument == filename or should_create_file_checker(filename)
  File "/Users/mnencia/.pyenv/versions/2.7.12/envs/test/lib/python2.7/site-packages/flake8/checker.py", line 412, in __init__
    self.display_name = self.processor.filename
AttributeError: 'NoneType' object has no attribute 'filename'
```

**Comment by mnencia** [comment]
I just noticed the 2nd error is different. Maybe it's a different bug.

I'm attaching my my .isort.cfg

```
10:51 $ cat .isort.cfg
[settings]
known_first_party=testing
known_third_party=setuptools,psycopg2,mock,pytest
skip=.tox
```

**Comment by cas--** [comment]
Ah it is something to do with empty `.isort.cfg`, I can replicate that:

```
$ touch .isort.cfg
$ flake8 __init__.py 
...
AttributeError: 'SortImports' object has no attribute 'out_lines'
```

**Comment by cas--** [comment]
Ah I have `not_skip = __init__.py` in my config so must be that, see if that works for you.

**Comment by cas--** [comment]
Ok I can replicate in the tests with `skip=test.py` so I'll sort a fix for this soon.

Fyi, the other error `no attribute 'filename'` would occur if there wasn't a file with that name.

**Comment by gforcada** [comment]
@mnencia @cas-- 2.1.2 is out!

Thanks for reporting and fixing!

Would you mind giving it a try?

**Comment by mnencia** [comment]
Thanks, it works perfectly.
