### ISSUE TITLE
Undeclared pep8 dependency

### ISSUE THREAD

**Issue by mnencia** [gforcada/flake8-isort#9]
flake8-isort depends from pep8 module, but the dependency is not declared. That was not an issue until flake8 dropped the pep8 dependency in favour of pycodestyle.

On a clean virtualenv with latest flake8 and flake8-isort, when you invoke flake8 you obtain a traceback:

```
 $ flake8
Traceback (most recent call last):
  File "/Users/mnencia/prj/barman/internal/.tox/flake8/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/Users/mnencia/prj/barman/internal/.tox/flake8/lib/python2.7/site-packages/flake8/main.py", line 28, in main
    flake8_style = get_style_guide(parse_argv=True)
  File "/Users/mnencia/prj/barman/internal/.tox/flake8/lib/python2.7/site-packages/flake8/engine.py", line 233, in get_style_guide
    kwargs['parser'], options_hooks = get_parser()
  File "/Users/mnencia/prj/barman/internal/.tox/flake8/lib/python2.7/site-packages/flake8/engine.py", line 74, in get_parser
    (extensions, parser_hooks, options_hooks, ignored) = _register_extensions()
  File "/Users/mnencia/prj/barman/internal/.tox/flake8/lib/python2.7/site-packages/flake8/engine.py", line 58, in _register_extensions
    checker = _load_entry_point(entry, verify_requirements=False)
  File "/Users/mnencia/prj/barman/internal/.tox/flake8/lib/python2.7/site-packages/flake8/engine.py", line 37, in _load_entry_point
    plugin = entry_point.resolve()
  File "/Users/mnencia/prj/barman/internal/.tox/flake8/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/mnencia/prj/barman/internal/.tox/flake8/lib/python2.7/site-packages/flake8_isort.py", line 6, in <module>
    import pep8
ImportError: No module named pep8
```

To workaround it is sufficient to manually install pep8.

**Comment by gforcada** [comment]
@mnencia thanks for noticing, would you mind providing a pull request?

**Comment by Surgo** [comment]
please release to pypi.

**Comment by gforcada** [comment]
@Surgo thanks for pointing it out, I totally forgot!

1.3 is released! https://pypi.python.org/pypi/flake8-isort

@mnencia thanks for the patch!

**Comment by mnencia** [comment]
You should thank @m-novikov who actually provided the patch, I only reported the issue.

**Comment by gforcada** [comment]
Uh, sorry I went with the autocomplete... @m-novikov thanks for the patch! @mnencia thanks for reporting!
